version: '3'

services:
  nginx:
    image: deenoize/nginx-reaction
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /opt/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /opt/nginx-proxy/html:/usr/share/nginx/html
      - /opt/nginx-proxy/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - /opt/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /opt/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /opt/nginx-proxy/html:/usr/share/nginx/html
      - /opt/nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - /opt/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /opt/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /opt/nginx-proxy/html:/usr/share/nginx/html
      - /opt/nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /opt/portainer/data:/data
    environment:
      - VIRTUAL_HOST=portainer.moneta.fund
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.moneta.fund
      - LETSENCRYPT_EMAIL=deenoize@gmail.com
    expose:
      - 9000

networks:
  default:
    nginx-proxy:
